services:
# ─────────── MySQL private service ───────────
- type: pserv
  name: mysql-db
  env: docker
  dockerfilePath: mysql.Dockerfile
  plan: starter
  disk:
    name: mysql-data
    mountPath: /var/lib/mysql
    sizeGB: 5
  envVars:
    - key: MYSQL_ROOT_PASSWORD
      generateValue: true
    - key: MYSQL_DATABASE
      value: appdb
    - key: MYSQL_USER
      value: appuser
    - key: MYSQL_PASSWORD
      value: appPass123

# ─────────── Node / Express API (web) ───────────
- type: web
  name: school-api
  env: docker
  dockerfilePath: Dockerfile
  plan: free
  autoDeploy: true
  envVars:
    - key: DB_HOST   
      value: mysql-db-zpkp
    - key: DB_PORT
      value: "3306"
    - key: DB_USER
      value: appuser
    - key: DB_PASSWORD
      value: appPass123
    - key: DB_NAME
      value: appdb
