services:
  # ──────────── 1. MySQL private service ────────────
  - type: pserv
    name: mysql-db
    env: docker
    repo: .
    dockerfilePath: mysql.Dockerfile
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: appuser
      - key: MYSQL_PASSWORD
        value: appPass123
    plan: starter

  # ──────────── 2. Node / Express web service ────────────
  - type: web
    name: school-api
    env: docker
    repo: .
    autoDeploy: true
    plan: free
    envVars:
      # internal host provided by Render
      - key: DB_HOST
        fromService:
          name: mysql-db
          property: host
      # internal port (3306) from same service
      - key: DB_PORT
        fromService:
          name: mysql-db
          property: port
      # static values that match your local .env
      - key: DB_USER
        value: appuser
      - key: DB_NAME
        value: appdb
      # pull the password Render already set on mysql‑db
      - key: DB_PASSWORD
        fromService:
          name:       mysql-db
          envVarKey:  MYSQL_PASSWORD
