services:
  # ─────────────────── MySQL private service ───────────────────
  - type: pserv
    name: mysql-db
    env: docker
    dockerfilePath: mysql.Dockerfile   
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: appuser
      - key: MYSQL_PASSWORD
        value: appPass123
    plan: starter                      

  # ─────────────────── Node / Express API ───────────────────
  - type: web
    name: school-api
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: DB_HOST
        fromService:
          type: service
          name: mysql-db
          property: host
      - key: DB_PORT
        fromService:
          type: service
          name: mysql-db
          property: port
      - key: DB_USER
        value: appuser
      - key: DB_NAME
        value: appdb
      - key: DB_PASSWORD
        fromService:
          type: service
          name: mysql-db
          envVarKey: MYSQL_PASSWORD
